add Lineage os plugin
ubports/ubports-installer pull request #1834
Opened 2021-03-07 21:21 UTC by Vince1171

**DO NOT merge until   progressive-downloader is updated to 1.0.7**
### Current limitations:
 * No LineageOS Recovery support (I haven't found {yet} an API for it)
 * only download the latest available image

### Usage: 
Select the channel (always nightly)
```
options:
      - var: "channel"
        name: "LineageOS version"
        tooltip: "Which LineageOS channel do you want to install?"
        type: "select"
        remote_values:
          lineage_os:channels:
```
Install the latest LineageOS zip (need `adb` and a ORS compatible recovery)
```
steps:
      - actions:
          - lineage_os:install:
```
Download the latest zip with the name `lineageos_rootfs_DEVICE.zip`
(used automatically by `lineage_os:install`)
```
steps:
      - actions:
          - lineage_os:download:
```

2021-03-07 21:32 UTC, NeoTheThird commented on src/core/plugins/lineage_os/api.js
> +
```suggestion
```

2021-03-08 09:26 UTC, NeoTheThird requested changes
awesome!

- [ ] (currently blocked by #1552) update progressive-downloader to 0.1.7
- [ ] document new steps as was done in https://github.com/ubports/installer-configs/pull/70

2021-03-22 19:23 UTC, Vince1171 commented
As  #1552 is still in progress, can this be merged? (with ubports/installer-configs#85)

2021-04-14 10:23 UTC, Vince1171 commented
ping @NeoTheThird

2021-09-26 14:21 UTC, NeoTheThird commented
My deepest apologies for the huge delay. Yes, let's go!

2021-09-26 14:22 UTC, merged